codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default: off
      unittest:
        flags: unittest
        target: 85%
flags:
  unittest:
    # only test unittests
    paths:
      - aliyun-net-sdk-core/

ignore:
  - "aliyun-net-sdk-core.Tests/" # ignore aliyun-net-sdk-core.Tests
  - "aliyun-sdk-feature-test/" # ignore aliyun-sdk-feature-test
