codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        target: 85%

ignore:
  - "aliyun-net-sdk-core.Tests/"  # ignore aliyun-net-sdk-core.Tests
  - "aliyun-net-sdk-ecs/"  #igonre aliyun-net-sdk-ecs
