codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default: off
      unittest:
        flags: unittest
        target: 85%
      featuretest:
        flags: featuretest
flags:
  unittest:
    # only test unittests
    paths:
      - aliyun-net-sdk-core.Tests/
  featuretest:
    # only test featuretest
    paths:
      - aliyun-net-feature-test/
