name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '2.x'
    - name: install altcover
      run: dotnet tool install --global altcover.visualizer --version 8.6.14
    - name: Install dependencies
      run: cd aliyun-net-sdk-core.Tests/ && dotnet add package AltCover --version 8.6.14 && cd ../ && dotnet restore && dotnet build
    - name: Test
      run: dotnet test aliyun-net-sdk-core.Tests/ /p:AltCover=true
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # required
